import Link from "next/link";
import { ArrowRight, CalendarClock, CircleAlert, Sparkles, TrendingUp, Users } from "lucide-react";

import { RevenueChart } from "@/components/dashboard/revenue-chart";
import { QuickAppointment } from "@/components/dashboard/quick-action";
import { StaffAvatar } from "@/components/staff-avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { authorize } from "@/domain/auth/permissions";
import { requirePermission } from "@/server/auth/authorization";
import { getDashboardData } from "@/server/data/dashboard";
import { db } from "@/server/db";

const euro = (cents: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(cents / 100);

export default async function DashboardPage() {
  const session = await requirePermission("appointments:view");
  const canViewFinance = authorize(session.role, "finance:view");
  const canEditAppointments = authorize(session.role, "appointments:edit");
  const canManageWaitlist = authorize(session.role, "waitlist:edit");
  const canViewInsights = authorize(session.role, "waitlist:view") || authorize(session.role, "products:view");
  const professionalStaff = session.role === "PROFESSIONAL" ? await db.staff.findFirst({ where: { tenantId: session.tenantId, userId: session.userId, deletedAt: null }, select: { id: true } }) : undefined;
  const data = await getDashboardData(session.tenantId, { professionalStaffId: professionalStaff?.id ?? (session.role === "PROFESSIONAL" ? null : undefined), canViewFinance });
  return (
    <div className="flex flex-col gap-6">
      <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs text-muted-foreground"><span className="size-2 rounded-full bg-white" /> Dados do tenant em tempo real</div><h1 className="font-heading text-3xl font-semibold tracking-[-.035em] sm:text-4xl">Olá, {session.name.split(" ")[0]}.</h1><p className="mt-2 text-sm text-muted-foreground">A visão abaixo é calculada a partir da operação registrada no banco.</p></div><div className="flex gap-2"><Button asChild variant="outline"><Link href="/agenda"><CalendarClock data-icon="inline-start" /> Ver agenda</Link></Button>{canEditAppointments ? <QuickAppointment tenantSlug={data.tenant.slug} /> : null}</div></section>

      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{data.metrics.map((metric, index) => <Card key={metric.label} className={index === 0 ? "border-primary/25 bg-primary/8" : "border-white/8"}><CardHeader className="pb-1"><CardDescription>{metric.label}</CardDescription></CardHeader><CardContent className="flex items-end justify-between"><p className="font-heading text-3xl font-semibold tracking-[-.04em]">{metric.value}</p><Badge variant={index === 0 ? "default" : "secondary"}>{metric.change}</Badge></CardContent></Card>)}</section>

      {canViewFinance ? <section className="grid gap-4 xl:grid-cols-[1.45fr_.75fr]"><Card className="border-white/8"><CardHeader className="flex-row items-start justify-between"><div><CardTitle className="font-heading">Faturamento em movimento</CardTitle><CardDescription>Receita realizada nos últimos 14 dias.</CardDescription></div><Badge variant="outline">Banco</Badge></CardHeader><CardContent><RevenueChart data={data.revenueTrend} /></CardContent></Card><Card className="overflow-hidden border-primary/20 bg-white/[.025]"><CardHeader><div className="mb-2 grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Sparkles /></div><CardTitle className="font-heading">Impacto registrado</CardTitle><CardDescription>Valores protegidos ou atribuídos pelos fluxos do sistema.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3"><p className="font-heading text-4xl font-semibold tracking-[-.05em]">{euro(data.impact.total)}</p>{[["Sinais", data.impact.deposits], ["Fila de espera", data.impact.waitlist], ["Campanhas", data.impact.campaigns]].map(([label, value]) => <div key={String(label)} className="flex items-center justify-between border-b border-white/8 pb-2 last:border-0"><p className="text-xs font-medium">{label}</p><span className="font-mono text-sm text-white">{euro(Number(value))}</span></div>)}</CardContent></Card></section> : null}

      <section className="grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Card className="border-white/8"><CardHeader className="flex-row items-center justify-between"><div><CardTitle className="font-heading">Agenda de hoje</CardTitle><CardDescription>{data.appointments.length} reservas encontradas.</CardDescription></div><Button asChild variant="ghost" size="sm"><Link href="/agenda">Agenda completa <ArrowRight data-icon="inline-end" /></Link></Button></CardHeader><CardContent><div className="flex flex-col gap-2">{data.appointments.slice(0, 6).map((appointment) => <div key={appointment.id} className="grid grid-cols-[3.5rem_1fr_auto] items-center gap-3 rounded-xl border border-white/8 p-3"><span className="font-mono text-xs text-muted-foreground">{appointment.time}</span><div><p className="text-sm font-medium">{appointment.customer}</p><p className="text-xs text-muted-foreground">{appointment.service} · {appointment.staff}</p></div><Badge variant="secondary">{appointment.status}</Badge></div>)}{data.appointments.length === 0 ? <p className="py-10 text-center text-sm text-muted-foreground">Nenhuma reserva hoje.</p> : null}</div></CardContent></Card><Card className="border-white/8"><CardHeader><CardTitle className="font-heading text-base">Horários livres hoje</CardTitle><CardDescription>Calculados para o serviço ativo mais curto.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{data.freeSlots.map((slot) => <div key={slot.time} className="flex items-center justify-between rounded-xl border border-dashed border-white/12 px-3 py-2.5"><div><span className="font-mono text-sm text-primary">{slot.time}</span><p className="mt-1 text-[11px] text-muted-foreground">{slot.staff || slot.fit}</p></div>{canManageWaitlist ? <Button asChild variant="ghost" size="sm"><Link href="/fila-de-espera">Preencher</Link></Button> : <Badge variant="outline">Livre</Badge>}</div>)}{data.freeSlots.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">Sem vagas futuras hoje.</p> : null}</CardContent></Card></section>

      <section className={canViewInsights ? "grid gap-4 lg:grid-cols-2" : "grid gap-4"}><Card className="border-white/8"><CardHeader className="flex-row items-center justify-between"><div><CardTitle className="font-heading">{session.role === "PROFESSIONAL" ? "Meu desempenho" : "Equipe"}</CardTitle><CardDescription>{canViewFinance ? "Receita e ocupação calculadas por profissional." : "Ocupação calculada a partir da jornada registrada."}</CardDescription></div><Users className="text-muted-foreground" /></CardHeader><CardContent className="flex flex-col gap-4">{data.staff.map((member, index) => <div key={member.id} className="grid grid-cols-[auto_1fr_auto] items-center gap-3"><StaffAvatar imageUrl={member.imageUrl} initials={member.initials} color={member.color} className="size-9" /><div><div className="flex justify-between gap-3 text-sm"><span>{member.name}</span><span className="font-mono">{canViewFinance ? euro(member.revenue) : `${member.occupancy}%`}</span></div><Progress value={member.occupancy} className="mt-2 h-1.5" /></div><Badge variant="outline">{session.role === "PROFESSIONAL" ? "Você" : `#${index + 1}`}</Badge></div>)}</CardContent></Card>{canViewInsights ? <Card className="border-white/8"><CardHeader><CardTitle className="font-heading">Insights</CardTitle><CardDescription>Regras determinísticas sobre estoque e fila.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{data.insights.map((insight) => <div key={insight.title} className="flex gap-3 rounded-xl border border-white/8 bg-white/[.018] p-3"><span className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg bg-white/10 text-white">{insight.kind === "warning" ? <CircleAlert className="size-4" /> : <TrendingUp className="size-4" />}</span><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{insight.title}</p><Badge variant="secondary">{insight.impact}</Badge></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{insight.detail}</p></div></div>)}</CardContent></Card> : null}</section>
    </div>
  );
}
